[Update] LKENodePool to use multi-item example
linode/linode-api-docs pull request #164
Opened 2019-11-27 20:19 UTC by leslitagordita

This example better represents the `linodes` property which returns an array of objects.

2019-11-27 20:24 UTC, leslitagordita commented
*Note:* This requires a front end fix before it can be merged in.

2019-12-02 18:45 UTC, displague commented
A `linode_id: null` example would also be useful to see.

2021-03-18 13:01 UTC, alioso commented
hi @leslitagordita ! I found out I am still assigned this review :) can we please close this?

2021-03-23 13:18 UTC, alioso approved these changes

2023-04-18 20:52 UTC, asauber requested changes
Looks like this should be closed.

2023-04-19 01:46 UTC, displague commented
Yes, this PR offers an example for the `linodes` field in the `LKENodePool` schema.
The example is now present through the `LKENodeStatus` schema property examples.  
This schema is embedded in the `nodes` property which replaced the `linodes` property in the OAS3 definition.

2023-04-19 01:48 UTC, displague commented
However, if it is still possible for an `id` to be null, that is a case that is not well documented in the spec or the examples.

2023-10-05 15:12 UTC, closed without merging