[Update] POST /object-storage/keys
linode/linode-api-docs pull request #341
Opened 2020-10-01 16:27 UTC by hzoppetti

- addded note to bucket_access field in object storage schema 
- updated description of create object storage keys endpoint

2020-10-01 21:02 UTC, leslitagordita approved these changes

2020-10-01 21:48 UTC, adammohammed requested changes

2020-10-01 21:48 UTC, adammohammed commented on openapi.yaml
> +              **Note:** If this field is ommited, a regular unlimited access key is issued.
`ommitted` -> `omitted`

2020-10-02 13:34 UTC, hzoppetti commented on openapi.yaml
> +              **Note:** If this field is ommited, a regular unlimited access key is issued.
fixed :)

2020-10-02 15:31 UTC, adammohammed approved these changes

2020-10-05 17:31 UTC, merged