VLANs and Interfaces Endpoints
linode/linode-api-docs pull request #345
Opened 2020-10-07 14:15 UTC by leslitagordita

VLANs List, VLAN Create, VLAN View, VLAN Delete, VLAN Attach, VLAN Detach

2020-10-14 20:43 UTC, aspsk requested changes
Looks great! Left some minor comments

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +                      * You can add up to 3 Network Interfaces, `eth0` - `eth2`.
Please move this below

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +                      * The Network Interfaces created by this field are also added to this Linode's
Is this phrase not finished?

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +
* If only `type: additional` interfaces are specified, then this Linode won't have direct access to public Internet. This way you can create truly private Linodes. You can add public interface to the default or a custom boot config later.

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +          The parameters to set when creating the Configuration profile.
Not `Configuration profile`

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +            A Configuration profile was created.
Interface

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +        description: Information about the domain you are registering.
domain?

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +          description: NodeBalancer created successfully.
Nodebalancer?

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +                https://api.linode.com/v4beta/networking/vlans/12345
would be cool to add output, like
```
{
  "id": 12345,
  "region": "us-east",
  "description": "woo",
  "linodes": [
    {
      "id": 123,
      "mac_address": "ba:ba:b1:54:50:01"
    }
  ],
  "cidr_block": null,
  "created": "2020-06-32T27:47:55"
}
```

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +            does not have a public Network Interface it will not receive a public IP address.
(Unless a boot config lists *no* interfaces. In this case for compatibility the Linode will be provided with a public interface.)

2020-10-14 20:43 UTC, aspsk commented on openapi.yaml
> +          example: f2:3c:92:8d:bc:00
🚫 this is a mac. Example is `10.0.0.123/24`

2021-03-31 19:53 UTC, alsaihn commented on openapi.yaml
> +            Interface labels must be unique within the data center region.
```suggestion
            Interface labels must be unique within this Linode's configuration profile.
```
Customers can and should add the same label to different linode configs, but they must be unique within a config.

2021-03-31 19:55 UTC, alsaihn commented on openapi.yaml
> +            Only used for type `vlan` interfaces. Enter an empty string for type `public` interfaces.
Can we note here that an empty string is allowed for the 'vlan' interfaces also? The customer would have to manually configure the network in this case.

2021-03-31 19:58 UTC, alsaihn commented on openapi.yaml
> +        A public interface in the first/eth0 position is automatically assigned the Linode's default public IPv4 address. Only one public interface per Linode can be defined. If no public interface i
A public interface can be in any position, but I'm not sure about the automatic parts if it's not in position 1.

2021-04-01 14:09 UTC, alsaihn reviewed
Could we add something about how adding/changing/removing interfaces is not sufficient by itself to make those changes happen on the linode? A reboot (or other workflow that causes the linode to be booted/restarted) is required for the networking changes to actually take effect. This gives customers the flexibility to make those changes and then have them take effect when convenient for them.

2021-04-02 12:31 UTC, yoshizzle approved these changes
I have the same comments as Carissa. The other things have been addressed.

2021-04-02 20:00 UTC, abemassry commented on openapi.yaml
> +            Must be unique among all interfaces in the data center region.
```suggestion
            Must be unique among all interfaces on the Linode.
```

2021-04-02 20:00 UTC, abemassry commented on openapi.yaml
> +            Configuring an IPAM address within the 10.0.0.0/8 block allows for automatic configuration with Network Helper. Addresses outside of this range must be configured manually.
```suggestion
            Configuring an IPAM address within the 10.0.0.0/8 block allows for automatic configuration with Network Helper, for example.
```

2021-04-02 20:02 UTC, abemassry commented on openapi.yaml
> +        A public interface in the first/eth0 position is automatically assigned the Linode's default public IPv4 address. Only one public interface per Linode can be defined. If no public interface i
```suggestion
        The the Linode's default public IPv4 address is automatically assigned to the public interface. Only one public interface per Linode can be defined. If no public interface is defined, the Linode will not be reachable via the public internet. Access can only be established via LISH or other Linodes connected by VLAN.
```

2021-04-02 20:04 UTC, abemassry commented on openapi.yaml
> +        To detach a Linode from a VLAN, remove the associated interface from the Linode's configuration, delete the configuration, or delete the Linode.
```suggestion
        To detach a Linode from a VLAN, remove the associated interface from the Linode's configuration, delete the configuration, and reboot or delete the Linode.
```

2021-04-05 19:27 UTC, alsaihn approved these changes

2021-04-05 20:01 UTC, yoshizzle approved these changes

2021-04-05 20:19 UTC, merged